# Generated by Django 4.2 on 2025-01-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Filmy',
            fields=[
                ('filmid', models.AutoField(db_column='FilmID', primary_key=True, serialize=False)),
                ('tytul', models.CharField(blank=True, db_column='Tytul', max_length=100, null=True)),
                ('opis', models.TextField(blank=True, db_column='Opis', null=True)),
                ('czastrwania', models.SmallIntegerField(blank=True, db_column='CzasTrwania', null=True)),
                ('rokprodukcji', models.SmallIntegerField(blank=True, db_column='RokProdukcji', null=True)),
                ('wiekodbiorcy', models.IntegerField(blank=True, db_column='WiekOdbiorcy', null=True)),
            ],
            options={
                'db_table': 'filmy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('gatunekid', models.AutoField(db_column='GatunekID', primary_key=True, serialize=False)),
                ('nazwagatunku', models.CharField(blank=True, db_column='NazwaGatunku', max_length=50, null=True)),
            ],
            options={
                'db_table': 'gatunek',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jezyki',
            fields=[
                ('jezykid', models.AutoField(db_column='JezykID', primary_key=True, serialize=False)),
                ('nazwa', models.CharField(blank=True, db_column='Nazwa', max_length=50, null=True)),
            ],
            options={
                'db_table': 'jezyki',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Klienci',
            fields=[
                ('klientid', models.AutoField(db_column='KlientID', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
            ],
            options={
                'db_table': 'klienci',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pracownicy',
            fields=[
                ('pracownikid', models.AutoField(db_column='PracownikID', primary_key=True, serialize=False)),
                ('imie', models.CharField(blank=True, db_column='Imie', max_length=50, null=True)),
                ('nazwisko', models.CharField(blank=True, db_column='Nazwisko', max_length=50, null=True)),
                ('login', models.CharField(blank=True, db_column='Login', max_length=255, null=True)),
                ('haslo', models.CharField(blank=True, db_column='Haslo', max_length=255, null=True)),
            ],
            options={
                'db_table': 'pracownicy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rezerwacje',
            fields=[
                ('rezerwacjaid', models.AutoField(db_column='RezerwacjaID', primary_key=True, serialize=False)),
                ('miejsce', models.CharField(blank=True, db_column='Miejsce', max_length=4, null=True)),
                ('datazlozenia', models.DateTimeField(blank=True, db_column='DataZlozenia', null=True)),
            ],
            options={
                'db_table': 'rezerwacje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rezyser',
            fields=[
                ('rezyserid', models.AutoField(db_column='RezyserID', primary_key=True, serialize=False)),
                ('imie', models.CharField(blank=True, db_column='Imie', max_length=50, null=True)),
                ('nazwisko', models.CharField(blank=True, db_column='Nazwisko', max_length=50, null=True)),
            ],
            options={
                'db_table': 'rezyser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salekinowe',
            fields=[
                ('salaid', models.AutoField(db_column='SalaID', primary_key=True, serialize=False)),
                ('numer', models.IntegerField(blank=True, db_column='Numer', null=True)),
                ('liczbamiejsc', models.SmallIntegerField(blank=True, db_column='LiczbaMiejsc', null=True)),
            ],
            options={
                'db_table': 'salekinowe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seanse',
            fields=[
                ('seansid', models.AutoField(db_column='SeansID', primary_key=True, serialize=False)),
                ('data', models.DateField(blank=True, db_column='Data', null=True)),
                ('godzina', models.TimeField(blank=True, db_column='Godzina', null=True)),
            ],
            options={
                'db_table': 'seanse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stanowisko',
            fields=[
                ('stanowiskoid', models.AutoField(db_column='StanowiskoID', primary_key=True, serialize=False)),
                ('nazwastanowiska', models.CharField(blank=True, db_column='NazwaStanowiska', max_length=50, null=True)),
            ],
            options={
                'db_table': 'stanowisko',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statusrezerwacji',
            fields=[
                ('statusid', models.AutoField(db_column='StatusID', primary_key=True, serialize=False)),
                ('nazwa', models.CharField(blank=True, db_column='Nazwa', max_length=50, null=True)),
            ],
            options={
                'db_table': 'statusrezerwacji',
                'managed': False,
            },
        ),
    ]
