# Generated by Django 4.2 on 2025-01-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmyKlient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(blank=True, db_column='Tytul', max_length=100, null=True)),
                ('opis', models.TextField(blank=True, db_column='Opis', null=True)),
                ('nazwagatunku', models.CharField(blank=True, db_column='NazwaGatunku', max_length=50, null=True)),
                ('imie', models.CharField(blank=True, db_column='Imie', max_length=50, null=True)),
                ('nazwisko', models.CharField(blank=True, db_column='Nazwisko', max_length=50, null=True)),
                ('czastrwania', models.SmallIntegerField(blank=True, db_column='CzasTrwania', null=True)),
                ('rokprodukcji', models.SmallIntegerField(blank=True, db_column='RokProdukcji', null=True)),
                ('wiekodbiorcy', models.IntegerField(blank=True, db_column='WiekOdbiorcy', null=True)),
            ],
            options={
                'db_table': 'filmyklient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RezerwacjaKlient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seansid', models.IntegerField(db_column='SeansID')),
                ('miejsce', models.CharField(blank=True, db_column='Miejsce', max_length=4, null=True)),
            ],
            options={
                'db_table': 'rezerwacjaklient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeansKlient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, db_column='Data', null=True)),
                ('godzina', models.TimeField(blank=True, db_column='Godzina', null=True)),
                ('salaid', models.IntegerField(db_column='SalaID')),
                ('tytul', models.CharField(blank=True, db_column='Tytul', max_length=100, null=True)),
                ('seansid', models.IntegerField(db_column='SeansID')),
                ('jezykDubbingu', models.CharField(blank=True, db_column='JezykDubbingu', max_length=50, null=True)),
                ('jezykNapisow', models.CharField(blank=True, db_column='JezykNapisow', max_length=50, null=True)),
            ],
            options={
                'db_table': 'seansklient',
                'managed': False,
            },
        ),
    ]
